/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-07 01:47:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class njoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("<link href=\"/resources/css/user/userNJoin.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write("\n");
      out.write("	  <div class=\"joinbox\">\n");
      out.write("  <div class=\"logobox\">\n");
      out.write("  <img alt=\"\" src=\"../../resources/images/user/logo.png\"> <br>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"formbox\">\n");
      out.write("\n");
      out.write("	<div id=\"carouselExampleDark\" class=\"carousel carousel-dark slide\">\n");
      out.write("\n");
      out.write("  <div class=\"carousel-inner\">\n");
      out.write("    <div class=\"carousel-item active \" data-bs-interval=\"10000\">\n");
      out.write("    <div class=\"centerbox\" style=\"width: 450px; height: 200px;\">\n");
      out.write("      <h3><img alt=\"\" src=\"/upload/profile/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.imgFile }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 30px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님께서 그동안 작성하신 게시물은 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfor[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개, 좋아요한 게시물은 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userinfor[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개 입니다.</h3>\n");
      out.write("      <a href=\"/member/mypage?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><h4>내 게시물 보러가기</h4></a>\n");
      out.write("  	</div>\n");
      out.write("  	<div class=\"confirmbtn\">\n");
      out.write("      정말로 탈퇴하시겠습니까? \n");
      out.write("  	</div>\n");
      out.write("<div class=\"btnbox\">\n");
      out.write("  <button type=\"button\" class=\"btncss\" data-bs-target=\"#carouselExampleDark\" data-bs-slide=\"next\">예</button>\n");
      out.write("  <a href=\"/board/list\"><button type=\"button\" class=\"btncss\">아니오</button></a>\n");
      out.write("  	</div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"carousel-item \" data-bs-interval=\"2000\">\n");
      out.write("    <div class=\"centerbox\" style=\"width: 510px; height: 378px; \">\n");
      out.write("    <div class=\"pwcheckbox\">\n");
      out.write("   <h3 style=\"text-align: left;\">회원 탈퇴를 진행하시려면 비밀번호를 입력해주세요.</h3>\n");
      out.write("    <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"id\" id=\"id\"> <br>\n");
      out.write("                        <input type=\"password\" class=\"form-control pwbox\" id=\"oldPw\">\n");
      out.write("                        <button type=\"button\" id=\"checkBtn\" class=\"btncss\">확인</button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"resultbox\">\n");
      out.write("   	\n");
      out.write("   	</div>\n");
      out.write("    </div>\n");
      out.write("                  <div id=\"btns\" class=\"btnbox\">\n");
      out.write("         \n");
      out.write(" 		 </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"carousel-item \">\n");
      out.write("    <div class=\"centerbox\" >\n");
      out.write("    <div class=\"tagment\">\n");
      out.write("    <h4>그동안 <img src=\"../../resources/images/user/logo.png\" style=\"width: 130px; background-color: gray;\">를 이용해주셔서 감사했습니다.</h4>\n");
      out.write("    </div>\n");
      out.write("     <div class=\"tagbox\">\n");
      out.write("            <a href=\"/member/removeuser?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button type=\"button\" id=\"exitbtn\">탈퇴하기</button></a>\n");
      out.write("            <p>위 버튼을 누르면 정말 탈퇴가 진행됩니다.</p>\n");
      out.write("            \n");
      out.write("                </div>\n");
      out.write("    </div>\n");
      out.write("              \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("     \n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("  \n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/user/userNJoin.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
